<?php

namespace Nemundo\Html\Container;


class TagContainer extends AbstractTagContainer
{


    /**
     * @var string
     */
    public $tagName;

    public function addHtml($html)
    {
        return parent::addHtml($html); // TODO: Change the autogenerated stub
    }


}