<?php

namespace Nemundo\Html\Script;


use Nemundo\Com\JavaScript\AbstractJavaScriptCode;

class JavaScriptFunction extends AbstractJavaScriptCode
{

    /**
     * @var string
     */
    public $functionName;


    public function addCodeLine($line)
    {
        return parent::addCodeLine($line); // TODO: Change the autogenerated stub
    }


    public function getCode()
    {

        $code = [];
        $code[] = 'function ' . $this->functionName . '() {';

        $code = array_merge($code, parent::getCode());

        $code[] = '}';

        return parent::getCode(); // TODO: Change the autogenerated stub
    }


}